// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bookmarks.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addBookmark = `-- name: AddBookmark :one
INSERT INTO bookmarks(user_id, post_id)
VALUES (
  $1,
  $2
)
RETURNING user_id, post_id
`

type AddBookmarkParams struct {
	UserID uuid.UUID
	PostID int32
}

func (q *Queries) AddBookmark(ctx context.Context, arg AddBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, addBookmark, arg.UserID, arg.PostID)
	var i Bookmark
	err := row.Scan(&i.UserID, &i.PostID)
	return i, err
}

const removeBookmark = `-- name: RemoveBookmark :exec
DELETE FROM bookmarks
WHERE user_id = $1 AND post_id = $2
`

type RemoveBookmarkParams struct {
	UserID uuid.UUID
	PostID int32
}

func (q *Queries) RemoveBookmark(ctx context.Context, arg RemoveBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, removeBookmark, arg.UserID, arg.PostID)
	return err
}
